# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cUCmC5ShnLeuu62piDfvep6twiX6yKe
"""

!pip install numpy matplotlib

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def f(x: np.ndarray) -> np.ndarray:
    """ベクトル場 dx/dt = x - x^3"""
    return x - x**3


def main() -> None:
    x = np.linspace(-2.0, 2.0, 2000)
    y = f(x)

    fig, ax = plt.subplots(figsize=(10, 5.5))

    # ベクトル場 F(x) = x - x^3
    ax.plot(
        x,
        y,
        linewidth=2.2,
        label=r"$\dot{x}=x-x^3$",
    )

    # x軸
    ax.axhline(
        0,
        linewidth=1.0,
    )

    # 大域アトラクタ A = [-1, 1]
    ax.axvspan(
        -1,
        1,
        alpha=0.15,
        label=r"global attractor $\mathcal{A}=[-1,1]$",
    )

    # モース集合
    # M_- = {-1}, M_0 = {0}, M_+ = {1}
    equilibria = [-1.0, 0.0, 1.0]

    labels = [
        r"$M_-=\{-1\}$" + "\n(stable)",
        r"$M_0=\{0\}$" + "\n(unstable)",
        r"$M_+=\{1\}$" + "\n(stable)",
    ]

    for x0, label in zip(equilibria, labels):
        ax.scatter(
            [x0],
            [0],
            s=110,
            zorder=5,
            edgecolor="black",
        )

        ax.annotate(
            label,
            xy=(x0, 0),
            xytext=(0, 18 if x0 == 0 else -48),
            textcoords="offset points",
            ha="center",
            fontsize=11,
        )

    # 軌道の進行方向
    intervals = [
        (-1.75, -1.25, 1),   # 右向き
        (-0.75, -0.25, -1),  # 左向き
        (0.25, 0.75, 1),     # 右向き
        (1.25, 1.75, -1),    # 左向き
    ]

    for x_start, x_end, direction in intervals:
        if direction > 0:
            start = x_start
            end = x_end
        else:
            start = x_end
            end = x_start

        ax.annotate(
            "",
            xy=(end, -0.18),
            xytext=(start, -0.18),
            arrowprops={
                "arrowstyle": "->",
                "linewidth": 2,
            },
        )

    # モースグラフの有向接続
    ax.annotate(
        r"$M_0 \rightarrow M_-$",
        xy=(-0.62, -0.18),
        xytext=(-0.62, -0.52),
        ha="center",
        fontsize=11,
    )

    ax.annotate(
        r"$M_0 \rightarrow M_+$",
        xy=(0.62, -0.18),
        xytext=(0.62, -0.52),
        ha="center",
        fontsize=11,
    )

    ax.set_title(
        r"Morse decomposition for $\dot{x}=x-x^3$"
    )

    ax.set_xlabel("$x$")
    ax.set_ylabel(r"$F(x)=x-x^3$")

    ax.set_xlim(-2, 2)
    ax.set_ylim(-2.7, 2.7)

    ax.grid(alpha=0.25)
    ax.legend(loc="upper right")

    fig.tight_layout()

    # 通常のPythonファイルとJupyter Notebookの両方に対応
    if "__file__" in globals():
        output_dir = Path(__file__).resolve().parent
    else:
        output_dir = Path.cwd()

    output = output_dir / "morse_decomposition.png"

    fig.savefig(
        output,
        dpi=200,
        bbox_inches="tight",
    )

    print(f"Saved: {output}")

    # Notebook上にもグラフを表示
    plt.show()


if __name__ == "__main__":
    main()